elastic/opentelemetry-lib

.github/workflows/ci.yml
Empty github workflow is expected to enable workflows and we should be able to test and merge https://github.com/elastic/opentelemetry-lib/pull/11/files post that.
=> Add empty github workflow for CI

remappers/common/const.go, remappers/hostmetrics/hostmetrics_test.go, remappers/internal/metric.go
Based on discussions with the team we will be adopting the [event.module](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-module) ECS attribute instead of `event.provider` to taint our remapped metrics.
=> Add event.module attribute to all remapped metrics

remappers/hostmetrics/cpu.go, remappers/hostmetrics/hostmetrics.go, remappers/hostmetrics/hostmetrics_test.go, remappers/hostmetrics/process.go, remappers/hostmetrics/processes.go
1. Push the processes scraper data to system.process.summary dataset
2. Add system.process.cmdline as attribute to processmetrics
3. Update the tests 
4. Rectify the name of iowait.pct in CPU scraper
5. Improve logic of calculating total number of processes
=> Fix issues in remappers

remappers/kubernetesmetrics/k8smetrics_test.go, remappers/kubernetesmetrics/kubelet.go
The metric k8s.pod.cpu.node.utilization is available in [v0.103.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.103.0/receiver/kubeletstatsreceiver/documentation.md#k8spodcpunodeutilization)
So we open this PR to add missing metrics from the remapper
=> Add k8s.pod.cpu.node.utilization metric in kubernetes remapper

remappers/hostmetrics/hostmetrics_test.go, remappers/hostmetrics/process.go
Relates: https://github.com/elastic/opentelemetry-dev/issues/296
Post the fix, the Process tab lights up
=> Add required metrics and datapoint attributes for Process tab in Host UI

remappers/hostmetrics/hostmetrics_test.go, remappers/hostmetrics/process.go, remappers/hostmetrics/processes.go
* Converts the `system.process.cpu.start_time` to a field with string date. The string date format allows the field to be correctly detected as a `date` field rather than an `int` field by the dynamic mapping used by APM. The date mapping is required by Kibana to parse the field correctly in the Process tab.
* Adds `event.dataset` for the process summary metric which is again required by the Process tab.
=> Send system.process.cpu.start_time as a field

remappers/kubernetesmetrics/k8smetrics_test.go
The benchmark was not doing anything since the scraper was incorrectly configured.
Bench results before the PR:
```
$ go test -run=^$ -bench=. ./...                                                     [9:03:18]
goos: darwin
goarch: arm64
pkg: github.com/elastic/opentelemetry-lib/remappers/kubernetesmetrics
BenchmarkRemap-10    	26727282	        44.76 ns/op	      28 B/op	       2 allocs/op
PASS
```
Bench results after the PR:
```
$ go test -run=^$ -bench=. ./...                                                                                                                                                     [9:04:04]
goos: darwin
goarch: arm64
pkg: github.com/elastic/opentelemetry-lib/remappers/kubernetesmetrics
BenchmarkRemap-10    	  446833	      2658 ns/op	    3800 B/op	     113 …
```
=> Fix k8s benchmark

remappers/common/const.go, remappers/hostmetrics/cpu.go, remappers/hostmetrics/disk.go, remappers/hostmetrics/filesystem.go, remappers/hostmetrics/hostmetrics.go, remappers/hostmetrics/hostmetrics_test.go, remappers/hostmetrics/load.go, remappers/hostmetrics/memory.go, remappers/hostmetrics/network.go, remappers/hostmetrics/process.go, remappers/hostmetrics/processes.go, remappers/internal/remappedmetric/metric.go, remappers/internal/remappedmetric/metric_test.go, remappers/internal/remappedmetric/mutator.go, remappers/kubernetesmetrics/clustermetrics.go, remappers/kubernetesmetrics/k8smetrics.go, remappers/kubernetesmetrics/k8smetrics_test.go, remappers/kubernetesmetrics/kubelet.go
Unlike `data_stream.dataset` which doesn't need to be set for the APM path, the `event.dataset` is required for multiple UI panels. The PR allows setting the dataset in all cases and adopts the mutator pattern throughout the codebase.
There are no major logic changes other than all metrics having `event.dataset` set as a datapoint attribute.
=> Add event.dataset to all remapped metrics

remappers/hostmetrics/process.go
In some scenarios, we have observed that the user.name is not fetched since ots corresponding OTEL metric(process.owner) is not present. 
But the absence of user.name leads to the process tab not working in Curated UI's. Hecne adding default value of "undefined" in case not present.
The same is done for system_cmdline for the same reasons
=> Handle user.name/system_cmdline if not present

remappers/common/const.go, remappers/hostmetrics/hostmetrics.go, remappers/hostmetrics/hostmetrics_test.go
`event.module` is required to make the Observability Overview panel work for the APM path.
=> Set event.module for hostmetrics remapper

enrichments/trace/config/config.go, enrichments/trace/config/config_test.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go, enrichments/trace/trace.go, enrichments/trace/trace_test.go
Allows enabling/disabling enrichment of specific attributes.
=> Add configuration to disable attribute enrichment

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/attributes.go, enrichments/trace/internal/elastic/resource.go, enrichments/trace/internal/elastic/resource_test.go
Adds enrichment for `agent.version` as per [apm-data](https://github.com/elastic/apm-data/blob/main/input/otlp/metadata.go)
=> [enrichments] Add agent.version

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/span.go
Initially, the plan was to deduce `trace.root` using OTTL support but that would not be available with the connector in the near future. So, creating a new key `trace.root`.
Also, removing the key `transaction.root` which was used to identify a transaction previously. We don't need this anymore in the latest version of how the pipeline works.
=> Remove txn.root and add trace.root as enrichment

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/attributes.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
Related to: https://github.com/elastic/opentelemetry-dev/issues/378
=> [enrichments] Add transaction.sampled

enrichments/trace/config/config.go, enrichments/trace/config/config_test.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
Adds `processor.event` enrichment for span events. Also, makes span events as a first class config and refactor code to add other enrichments for span events (for example: `exception.stacktrace`)
Related to: https://github.com/elastic/opentelemetry-dev/issues/372
=> [enrichments] Add processor.event for span events

remappers/hostmetrics/hostmetrics.go, remappers/hostmetrics/hostmetrics_test.go, remappers/kubernetesmetrics/k8smetrics.go, remappers/kubernetesmetrics/k8smetrics_test.go
Scraper names were changed in v0.107.0: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34526/files
Breaking change: https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.107.0
=> fix: udate hostmetrics scrapers names

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/attributes.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
Related to: https://github.com/elastic/opentelemetry-lib/issues/86
=> [enrichment/trace] Handle exception for span events

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/attributes.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
`error.grouping_name` is set in APM using an ingest-pipeline: https://github.com/elastic/elasticsearch/blob/a18b3313364b6b7c87c45bae9dc342dec314966d/x-pack/plugin/apm-data/src/main/resources/component-templates/logs-apm.error%40mappings.yaml#L25-L42. For OTel, based on apm-data logic, it basically translates to a 1<>1 mapping for `error.exception.message`. However, it is derived in nature and could its definition could be extended in future so keeping it as enrichment - let me know if there are any concerns.
Related to: https://github.com/elastic/opentelemetry-dev/issues/317
=> Add enrichment for error.grouping_name

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/resource.go, enrichments/trace/internal/elastic/resource_test.go
// Host name is set same as k8s node name. In case, both host name
// and k8s node name are set then host name is overridden as this is
// considered an invalid configuration/smell and k8s node name is
// given higher preference.
For more context: https://elastic.slack.com/archives/C07Q1CVD9MW/p1728487638317189
=> [enrichments]Allow overriding host name with k8s node name

enrichments/trace/internal/elastic/resource.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
`http.url` is still being used. This PR adds support for the now deprecated `http.url` in addition to `url.full`. There are a couple more attributes for `net.peer.*` which I am working on resolving.
Related to: https://github.com/elastic/opentelemetry-dev/issues/490
=> Add support for http.url to identify url full

enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
`service.{address, port}` is used to calculate service destination when `url.*` attributes are not present. The logic fallback to use the now deprecated `net.peer.{name, port}` if `service.{address, port}` are not present.
Related to: https://github.com/elastic/opentelemetry-dev/issues/490
=> Support service.{address, port} with fallback to net.peer.*

agentcfg/elasticsearch.go, agentcfg/elasticsearch_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, go.mod, go.sum
Files from https://github.com/elastic/opentelemetry-collector-components/pull/310 so it can be reused in multiple projects.
=> feat: add apm agent configuration package

enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go
In the OTel data model it's allowed (and not very uncommon) to have a root span which in itself represents a dependency. Such spans are root and exit span at the same time.
Examples can be seen in the tests (e.g. outgoing HTTP call, just a span without root that represents a db call or produces a message). Such spans are mapped into a transaction, because in the Elastic data model we always need a transaction as root.
This PR adds logic to enrich such transactions with the necessary fields to calculate dependencies and draw a service map.
Follow up PR in Kibana will still need to be done to query such transactions - currently only `processor.event: span` is used for dependencies. This PR adds all the necessary fields, so then those queries can be updated and filtering on `processor.event` …
=> Enrich root spans that represent a dependency

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/span.go, enrichments/trace/internal/elastic/span_test.go, enrichments/trace/trace.go, go.mod, go.sum
Adds enrichment for `user_agent.{name, version}` if it is missing. The attributes are derived from `user_agent.original`.
Closes: https://github.com/elastic/opentelemetry-lib/issues/172
=> Add enrichment for user_agent.{name, version}

enrichments/trace/config/config.go, enrichments/trace/internal/elastic/resource.go, enrichments/trace/internal/elastic/resource_test.go
`deployment.environment.name`  was introduced in SemConv  [v1.27.0](https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.27.0) and `deployment.environment` got deprecated.
In the `otel-data` ES plugin we alias `service.environment` to `deployment.environment`.  `service.environment` is used by Kibana to show the environment.
In this PR, if `deployment.environment.name` is set, we duplicate it into `deployment.environment` in order to make the `service.environment` -> `deployment.environment` work.
So far there is no better solution on the table - ideally we'd need an ES feature where the `service.environment` alias has two targets, but currently that is not possible in ES.
=> Handle deployment.environment.name

remappers/hostmetrics/cpu.go, remappers/hostmetrics/hostmetrics_test.go
Don't warn if system.cpu.logical.count is missing, as it's an optional metric. The warning is particularly unhelpful in gateway deployments, where the central operations team has no control over what is being sent to the gateway.
=> hostmetrics: don't warn on missing metrics
